app/main/views.py
from flask import Blueprint, render_template, request
from ..model import Post
from sqlalchemy import desc
from app import db
main = Blueprint("main", __name__)


@main.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    post = db.session.query(Post).order_by(desc(Post.id)).paginate(page=page, per_page=6)
    return render_template("homepage.html", post = post)
        

@main.route("/about")
def about():
    return render_template("about.html")

@main.app_context_processor
def context_processor():
    posts = db.session.query(Post).order_by(Post.id.desc()).group_by(Post.categories).limit(9)
    #posts = db.session.query(Post).filter(Post.id == db.session.query(max(Post.id)))
    #posts = Post.query.filter_by(id = 1).first()

    page = request.args.get("page", 1, type=int)
    post = db.session.query(Post).order_by(desc(Post.id)).limit(6)
    post1 = db.session.query(Post).order_by(desc(Post.categories)).paginate(page=page, per_page=4)
    return dict(posts = posts, header_post=post, carousel_post = post1)

app/posts/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash, abort
from app import db
from flask_login import login_required, current_user
from sqlalchemy import desc
from .forms import PostForm, UpdatePostForm 
from ..model import Post, User
from .utils import save_post_img

posts = Blueprint("posts", __name__)


@posts.route("/post", methods = ["POST", "GET"])
@login_required
def post():
    form = PostForm()
    if request.method =="POST":
        if form.validate_on_submit():
            if form.post_img.data:
                post_img_file = save_post_img(form.post_img.data)
            post = Post(title = form.title.data,
                         content= form.content.data,
                        author = current_user,
                        featured_image = post_img_file,
                        categories=form.categories.data)
            db.session.add(post)
            db.session.commit()
            flash("Post Created successfully", "success")
        return redirect(url_for("main.index"))
    elif request.method == "GET":
        return render_template("create_post.html", form=form , title="Create Post", legend ="Create Post")

@posts.route("/blog/<int:post_id>")
def blog(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("blog.html", post=post)

@posts.route("/blog/<int:post_id>/update", methods = ["POST", "GET"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = UpdatePostForm()
    if form.validate_on_submit():
        if form.title.data:
            post.title = form.title.data
        if form.content.data:
            post.content = form.content.data
        if form.categories.data:
            post.categories = form.categories.data
        if form.post_img.data:
            post_img_file = save_post_img(form.post_img.data)
            post.featured_image = post_img_file
        db.session.commit()
        flash("Your post has been Updated", "success")
        return redirect(url_for("posts.blog", post_id = post.id))
    form.title.data = post.title
    form.content.data = post.content
    return render_template("update_post.html", form=form, title="Update Post", legend ="Update Post")

@posts.route("/blog/<int:post_id>/delete", methods = ["POST", "GET"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted", "success")
    return redirect(url_for("main.index"))


@posts.route("/user/<string:username>")
def user_post(username):
    user = User.query.filter_by(username = username).first_or_404()
    page = request.args.get("page", 1, type=int)
    post = db.session.query(Post).filter_by(author=user)\
                                .order_by(desc(Post.id))\
                                .paginate(page=page, per_page=6)
    return render_template("user_posts.html", post = post, user=user)

@posts.route("/categories/<string:categories>")
def categories_post(categories):
    page = request.args.get("page", 1, type=int)
    post = db.session.query(Post).filter_by(categories = categories)\
                                .order_by(desc(Post.id))\
                                .paginate(page=page, per_page=6)
    return render_template("categories_post.html", post = post, categories = categories)

app/templates/about.html
{% extends "base.html" %}
{% block content %}
<h1>About Page</h1>
{% endblock %}

app/templates/account.html
{% extends "base.html" %}
{% block content %}
{% from "macro.html" import render_field %}
<div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{image_file}}">
      <div class="media-body">
        <h2 class="account-heading">{{current_user.username}}</h2>
        <p class="text-secondary">{{current_user.email}}</p>
      </div>
    </div>
    <!-- FORM HERE -->
    <form class="form-group" action="/account" method="post" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Account Info</legend>
        <div class="form-group mt-2">
            {{form.username.label(class="form-control-label")}}
            {{render_field(form.username)}}
        </div>
        <div class="form-group mt-2">
            {{form.email.label(class="form-control-label")}}
            {{render_field(form.email)}}
            
        </div>
        <div class="form-group mt-4">
            {{form.picture.label}}<br>
            {{render_field(form.picture, class="form-control-file")}}
            
        </div>
    </fieldset>
    <div class="form-group mt-4">
        {{form.submit(class="btn btn-outline-info")}}
    </div>
    </form>
  </div>
{% endblock %}

app/templates/blog.html
{% extends "base.html" %}
{% block content %}
 <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
      </div class="container">
      <a href="{{url_for('posts.user_post', username=post.author.username)}}"><img class="rounded-circle article-img" 
        src="{{url_for('static', filename='profile_pics' + post.author.image_file)}}"></a>
      </div>
        <a class="mr-2" href="{{url_for('posts.user_post', username=post.author.username)}}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
        <div>
            <a class="btn btn-primary btn-sm " href="{{url_for('posts.update_post', post_id = post.id)}}">Edit</a>

            <button class="btn btn-danger btn-sm" data-bs-toggle="modal" 
            data-bs-target="#deleteModal" href="{{url_for('posts.update_post', post_id = post.id)}}">Delete</button>
        </div>
        {% endif %}
        <p>
        <h2><a class="article-title">{{ post.title }}</a></h2>
        <img class="post_img_blog" src="{{url_for('static', filename='post_img' + post.featured_image)}}">
        <p class="article-content">{{ post.content }}</p>
        </p>
      </article> 
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this post?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
          <form action="{{url_for('posts.delete_post', post_id=post.id)}}" method="post">
            <button type="submit" class="btn btn-danger">Delete Post</button>
          </form>
          
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/categories_post.html
{% extends "base.html" %}
{% block content %}
<h1 class="mb-3">Category: {{categories}} ({{post.total}})</h1>
<article class="media content-section">
  <div class="media-body">
    <div class="container">
      <div class="row">
        {% for post in post.items %}
        <div class="col-md-6 post-container">
          <div class="article-metadata">
            <div class="container">
              <a href="{{url_for('posts.user_post', username=post.author.username)}}"><img class="rounded-circle article-img" 
                src="{{url_for('static', filename='profile_pics' + post.author.image_file)}}"></a>
            </div>
            <a class="mr-2" href="{{url_for('posts.user_post', username=post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-primary">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <p>
            <h2>
              <a class="article-title" href="{{url_for('posts.blog', post_id=post.id)}}">{{ post.title }}</a>
            </h2>
            <img class="post_img" src="{{url_for('static', filename='post_img' + post.featured_image)}}">
            <p class="article-content">{{ post.content |truncate(250, True, '...') }}<a
                href="{{url_for('posts.blog', post_id=post.id)}}">Read More</a></p>
            </p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</article>
<div style="float:right;">
{% for page_number in post.iter_pages(left_edge =2, right_edge =2, left_current = 2, right_current =2) %}
{% if page_number %}
    {% if post.page == page_number %}
    <a class="btn btn-primary" href="{{url_for('posts.categories_post', categories=categories, page=page_number)}}">{{page_number}}</a>
    {% else %}
    <a class="btn btn-outline-primary" href="{{url_for('posts.categories_post', categories=categories, page=page_number)}}">{{page_number}}</a>
    {% endif %}
 {% else %}
 ...
{% endif %}
{% endfor %}
</div>
{% endblock content %}

app/templates/create_post.html
{% extends "base.html" %}
{% block content %}
{% from "macro.html" import render_field %}
<div class="content-section">
<form class="form-group" action="" method="post" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{legend}}</legend>
        <div class="form-group mt-2">
            {{form.title.label(class="form-control-label")}}
            {{render_field(form.title)}}
        </div>
        <div class="form-group mt-2">
            {{form.content.label(class="form-control-label")}}
            {{render_field(form.content)}}

        </div>
        <div class="form-group mt-2">
            {{form.categories.label(class="form-control-label")}}
            {{render_field(form.categories)}}

        </div>
        <div class="form-group mt-4">
            {{form.post_img.label}}<br>
            {{render_field(form.post_img, class="form-control-file", required=required)}}

        </div>
    </fieldset>
    <div class="form-group mt-4">
        {{form.submit(class="btn btn-outline-info btn-info", style="color:#fff;")}}
    </div>
</div>
    {% endblock %}

app/templates/homepage.html
{% extends "base.html" %}
{% block content %}

<!--Container-->
<div class="container">
    <div class="row mb-2">
        <div class="col-12 text-center pt-3">
            <h1 class="aofa">TELL THEM AOFA</h1>
            <p>THEY WAN HEAR THE GIST, <a href="/register" class="tagline">TELL THEM</a></p>
        </div>
    </div>

    <!--Start code-->
    <div class="row">
        <div class="col-12 pb-5">
            <!--SECTION START-->
            <section class="row">

                <!--Start slider news-->
                <div class="col-12 col-md-6 pb-0 pb-md-3 pt-2 pr-md-1">
                    <div id="featured" class="carousel slide carousel" data-bs-ride="carousel">
                        <!--dots navigate-->
                        <ol class="carousel-indicators top-indicator">
                            <li data-bs-target="#featured" data-bs-slide-to="0" class="active"></li>
                            <li data-bs-target="#featured" data-bs-slide-to="1"></li>
                            <li data-bs-target="#featured" data-bs-slide-to="2"></li>
                            <li data-bs-target="#featured" data-bs-slide-to="3"></li>
                        </ol>

                        <!--carousel inner-->
                        <div class="carousel-inner">
                            {% for post in carousel_post.items %}
                            <!--Item slider-->
                            <div class="carousel-item active">
                                <div class="card border-0 rounded-0 text-light overflow zoom">
                                    <div class="position-relative">
                                        <!--thumbnail img-->
                                        <div class="ratio_left-cover-1 image-wrapper">
                                            <a href="{{url_for('posts.blog', post_id=post.id)}}">
                                                <img class="img-fluid w-100 carousel_featured_image"
                                                    src="{{url_for('static', filename='post_img' + post.featured_image)}}"
                                                    alt="featured_image">
                                            </a>
                                        </div>
                                        <div class="position-absolute p-2 p-lg-3 b-0 w-100 bg-shadow">
                                            <!--title-->
                                            <a href="{{url_for('posts.blog', post_id=post.id)}}">
                                                <h2 class="h3 post-title text-white my-1">{{post.title |truncate(50,
                                                    True, '...') }}</h2>
                                            </a>
                                            <!-- meta title -->
                                            <div class="news-meta">
                                                <span class="news-author">by <a class="text-white font-weight-bold"
                                                        href="{{url_for('posts.user_post', username=post.author.username)}}">{{post.author.username}}</a></span>
                                                <span class="news-date">{{post.date_posted.strftime('%Y-%m-%d')}}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                            <!--end item slider-->
                        </div>
                        <!--end carousel inner-->
                    </div>

                    <!--navigation-->
                    <a class="carousel-control-prev" href="#featured" role="button" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only text-light"></span>
                    </a>
                    <a class="carousel-control-next" href="#featured" role="button" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only text-light"></span>
                    </a>
                </div>
                <!--End slider news-->

                <!--Start box news-->
                <div class="col-12 col-md-6 pt-2 pl-md-1 mb-3 mb-lg-4">
                    <div class="row">
                        <!--news box-->
                        {% for post in header_post %}
                        <div class="col-6 pb-1 pt-0 pr-1">
                            <div class="card border-0 rounded-0 text-white overflow zoom">
                                <div class="position-relative">
                                    <!--thumbnail img-->
                                    <div class="ratio_right-cover-2 image-wrapper">
                                        <a href="#">
                                            <img class="img-fluid header_image"
                                                src="{{url_for('static', filename='post_img' + post.featured_image)}}"
                                                alt="">
                                        </a>
                                    </div>
                                    <div class="position-absolute p-2 p-lg-3 b-0 w-100 bg-shadow">
                                        <!-- category -->
                                        <a class="p-1 badge badge-primary rounded-0"
                                            href="{{url_for('posts.categories_post', categories=post.scategories)}}">{{post.categories}}</a>

                                        <!--title-->
                                        <a href="{{url_for('posts.blog', post_id=post.id)}}">
                                            <h2 class="h5 text-white my-1">{{post.title |truncate(50, True, '...') }}
                                            </h2>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!--end news box-->
                    </div>
                </div>
                <!--End box news-->
            </section>
            <!--END SECTION-->
        </div>
    </div>
    <!--end code-->
</div>


<article class="media content-section">
    <div class="media-body">
        <div class="container">
            <div class="row">
                {% for post in post.items %}
                <div class="col-md-6 post-container">
                    <div class="article-metadata">
                        <div class="container">
                            <a href="{{url_for('posts.user_post', username=post.author.username)}}"><img
                                    class="rounded-circle article-img"
                                    src="{{url_for('static', filename='profile_pics' + post.author.image_file)}}"></a>
                        </div>
                        <a class="mr-2" href="{{url_for('posts.user_post', username=post.author.username)}}">{{
                            post.author.username }}</a>
                        <span class="text-primary"><a
                                href="{{url_for('posts.categories_post', categories=post.categories)}}">Category : {{
                                post.categories}}</a></span>
                        <small class="text-primary">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                        <p>
                        <h3>
                            <a class="article-title" href="{{url_for('posts.blog', post_id=post.id)}}">{{ post.title
                                }}</a>
                        </h3>
                        <img class="post_img" src="{{url_for('static', filename='post_img' + post.featured_image)}}">
                        <p class="article-content">{{ post.content |truncate(250, True, '...') }}<a
                                href="{{url_for('posts.blog', post_id=post.id)}}">Read More</a></p>
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</article>
<div style="float:right;">
    {% for page_number in post.iter_pages(left_edge =2, right_edge =2, left_current = 2, right_current =2) %}
    {% if page_number %}
    {% if post.page == page_number %}
    <a class="btn btn-primary" href="{{url_for('main.index', page=page_number)}}">{{page_number}}</a>
    {% else %}
    <a class="btn btn-outline-primary" href="{{url_for('main.index', page=page_number)}}">{{page_number}}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
</div>
{% endblock content %}

app/templates/login.html
{% extends "base.html" %}
{% block content %}
{% from "macro.html" import render_field, checkbox%}
<div class="content-section">
    <form class="form-group" action="/login" method="post">
    {{form.hidden_tag()}}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Login</legend>
        <div class="form-group mt-2">
            {{form.email.label(class="form-control-label")}}
            {{render_field(form.email)}}
            
        </div>
        <div class="form-group mt-2">
            {{form.password.label(class="form-control-label")}}
            {{render_field(form.password)}} 
        </div>
        <div class="form-group mt-2">
            <span>{{checkbox(form.remember)}} Remember Me</span>
        </div>
    </fieldset>
    <div class="form-group mt-4">
        {{form.submit(class="btn btn-outline-info")}}
    </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Forget Password? <a href="{{url_for('users.reset_request')}}">reset</a>
        </small>
    </div>
</div>

{% endblock%}

app/templates/macro.html
{% macro render_field(field)%}
{{field(class_="form-control form-control-lg", **kwargs)|safe}}
{%if field.errors %}
{%for error in field.errors %}
<pre style="color:red;">
{{error}}
</pre>
{% endfor %}
{%endif%}
{%endmacro%}
{% macro checkbox(field)%}
{{field(class_="form-check-input", **kwargs)|safe}}
{% endmacro %}

app/templates/register.html
{% extends "base.html" %}
{% block content %}
{% from "macro.html" import render_field, checkbox%}
<div class="content-section">
    <form class="form-group" action="/register" method="post">
    {{form.hidden_tag()}}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Join AOFA</legend>
        <div class="form-group mt-2">
            {{form.username.label(class="form-control-label")}}
            {{render_field(form.username)}}
        </div>
        <div class="form-group mt-2">
            {{form.email.label(class="form-control-label")}}
            {{render_field(form.email)}}
            
        </div>
        <div class="form-group mt-2">
            {{form.password.label(class="form-control-label")}}
            {{render_field(form.password)}}
            
        </div>
        <div class="form-group mt-2">
            {{form.confirm_password.label(class="form-control-label")}}
            {{render_field(form.confirm_password)}}
        </div>
    </fieldset>
    <div class="form-group mt-4">
        {{form.submit(class="btn btn-outline-info")}}
    </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an Account? <a href="{{url_for('users.login')}}">Sign In</a>
        </small>
    </div>
</div>

{% endblock%}

app/templates/request_reset.html
{% extends "base.html" %}
{% block content %}
{% from "macro.html" import render_field, checkbox%}
<div class="content-section">
    <form class="form-group" action="" method="post">
    {{form.hidden_tag()}}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Request Reset Password</legend>
        <div class="form-group mt-2">
            {{form.email.label(class="form-control-label")}}
            {{render_field(form.email)}}
        </div>
    </fieldset>
    <div class="form-group mt-4">
        {{form.submit(class="btn btn-outline-primary")}}
    </div>
    </form>
</div>

{% endblock%}

app/templates/reset.html
{% extends "base.html" %}
{% block content %}
{% from "macro.html" import render_field %}
<div class="content-section">
    <form class="form-group" action="" method="post">
    {{form.hidden_tag()}}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Request Reset Password</legend>
        <div class="form-group mt-2">
            {{form.password.label(class="form-control-label")}}
            {{render_field(form.password)}}
        </div>
        <div class="form-group mt-2">
            {{form.confirm_password.label(class="form-control-label")}}
            {{render_field(form.confirm_password)}}
        </div>
    </fieldset>
    <div class="form-group mt-4">
        {{form.submit(class="btn btn-outline-info")}}
    </div>
    </form>
</div>

{% endblock%}

app/templates/update_post.html
{% extends "base.html" %}
{% block content %}
{% from "macro.html" import render_field %}
<div class="content-section">
<form class="form-group" action="" method="post" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{legend}}</legend>
        <div class="form-group mt-2">
            {{form.title.label(class="form-control-label")}}
            {{render_field(form.title)}}
        </div>

        <div class="form-group mt-2">
            {{form.content.label(class="form-control-label")}}
            {{render_field(form.content)}}
        </div>

        <div class="form-group mt-2">
            {{form.categories.label(class="form-control-label")}}
            {{render_field(form.categories)}}
        </div>

        <div class="form-group mt-4">
            {{form.post_img.label}}<br>
            {{render_field(form.post_img, class="form-control-file")}}
        </div>

    </fieldset>
    <div class="form-group mt-4">
        {{form.submit(class="btn btn-outline-info btn-info", style="color:#fff;")}}
    </div>
</div>
    {% endblock %}

app/templates/user_posts.html
{% extends "base.html" %}
{% block content %}
<h1 class="mb-3">Posted by {{user.username}} <span>Total Post {{post.total}}</span></h1>
<article class="media content-section">
  <div class="media-body">
    <div class="container">
      <div class="row">
        {% for post in post.items %}
        <div class="col-md-6 post-container">
          <div class="article-metadata">
            <div class="container">
              <a href="{{url_for('posts.user_post', username=post.author.username)}}"><img class="rounded-circle article-img" 
                src="{{url_for('static', filename='profile_pics' + post.author.image_file)}}"></a>
            </div>
            <a class="mr-2" href="{{url_for('posts.user_post', username=post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-primary">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <span class="text-primary"><a href="{{url_for('posts.categories_post', categories=post.categories)}}"> Categories: {{ post.categories}}</a></span>
            <p>
            <h2>
              <a class="article-title" href="{{url_for('posts.blog', post_id=post.id)}}">{{ post.title }}</a>
            </h2>
            <img class="post_img" src="{{url_for('static', filename='post_img' + post.featured_image)}}">
            <p class="article-content">{{ post.content |truncate(250, True, '...') }}<a
                href="{{url_for('posts.blog', post_id=post.id)}}">Read More</a></p>
            </p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</article>
<div style="float:right;">
{% for page_number in post.iter_pages(left_edge =2, right_edge =2, left_current = 2, right_current =2) %}
{% if page_number %}
    {% if post.page == page_number %}
    <a class="btn btn-primary" href="{{url_for('posts.user_post', username= user.username, page=page_number)}}">{{page_number}}</a>
    {% else %}
    <a class="btn btn-outline-primary" href="{{url_for('posts.user_post', username= user.username, page=page_number)}}">{{page_number}}</a>
    {% endif %}
 {% else %}
 ...
{% endif %}
{% endfor %}
</div>
{% endblock content %}